const codes = [
  ['AGO', 'Angola'],
  ['AIA', 'Anguilla'],
  ['ARG', 'Argentina'],
  ['ASM', 'American Samoa'],
  ['ATG', 'Antigua and Barbuda'],
  ['AUS', 'Australia'],
  ['BDI', 'Burundi'],
  ['BEN', 'Benin'],
  ['BFA', 'Burkina Faso'],
  ['BGD', 'Bangladesh'],
  ['BHS', 'Bahamas'],
  ['BLZ', 'Belize'],
  ['BOL', 'Bolivia, Plurinational State of'],
  ['BRA', 'Brazil'],
  ['BRB', 'Barbados'],
  ['BTN', 'Bhutan'],
  ['BWA', 'Botswana'],
  ['CAF', 'Central African Republic'],
  ['CHL', 'Chile'],
  ['CIV', "Côte d'Ivoire"],
  ['CMR', 'Cameroon'],
  ['COD', 'Congo, the Democratic Republic of the'],
  ['COG', 'Congo'],
  ['COL', 'Colombia'],
  ['COM', 'Comoros'],
  ['CPV', 'Cape Verde'],
  ['CRI', 'Costa Rica'],
  ['CYM', 'Cayman Islands'],
  ['DJI', 'Djibouti'],
  ['DMA', 'Dominica'],
  ['DOM', 'Dominican Republic'],
  ['DZA', 'Algeria'],
  ['ECU', 'Ecuador'],
  ['EGY', 'Egypt'],
  ['ERI', 'Eritrea'],
  ['FJI', 'Fiji'],
  ['FSM', 'Micronesia, Federated States of'],
  ['GAB', 'Gabon'],
  ['GHA', 'Ghana'],
  ['GIN', 'Guinea'],
  ['GLP', 'Guadeloupe'],
  ['GMB', 'Gambia'],
  ['GNB', 'Guinea-Bissau'],
  ['GNQ', 'Equatorial Guinea'],
  ['GRD', 'Grenada'],
  ['GTM', 'Guatemala'],
  ['GUF', 'French Guiana'],
  ['GUM', 'Guam'],
  ['GUY', 'Guyana'],
  ['HKG', 'Hong Kong'],
  ['HND', 'Honduras'],
  ['HTI', 'Haiti'],
  ['IDN', 'Indonesia'],
  ['JAM', 'Jamaica'],
  ['JPN', 'Japan'],
  ['KAZ', 'Kazakhstan'],
  ['KGZ', 'Kyrgyzstan'],
  ['KHM', 'Cambodia'],
  ['KIR', 'Kiribati'],
  ['KNA', 'Saint Kitts and Nevis'],
  ['KOR', 'Korea, Republic of'],
  ['LAO', "Lao People's Democratic Republic"],
  ['LBR', 'Liberia'],
  ['LBY', 'Libyan Arab Jamahiriya'],
  ['LCA', 'Saint Lucia'],
  ['LKA', 'Sri Lanka'],
  ['LSO', 'Lesotho'],
  ['MAC', 'Macao'],
  ['MDG', 'Madagascar'],
  ['MDV', 'Maldives'],
  ['MEX', 'Mexico'],
  ['MHL', 'Marshall Islands'],
  ['MLI', 'Mali'],
  ['MNG', 'Mongolia'],
  ['MNP', 'Northern Mariana Islands'],
  ['MOZ', 'Mozambique'],
  ['MRT', 'Mauritania'],
  ['MSR', 'Montserrat'],
  ['MUS', 'Mauritius'],
  ['MYS', 'Malaysia'],
  ['MYT', 'Mayotte'],
  ['NAM', 'Namibia'],
  ['NCL', 'New Caledonia'],
  ['NER', 'Niger'],
  ['NGA', 'Nigeria'],
  ['NIC', 'Nicaragua'],
  ['NPL', 'Nepal'],
  ['NRU', 'Nauru'],
  ['NZL', 'New Zealand'],
  ['PAK', 'Pakistan'],
  ['PAN', 'Panama'],
  ['PER', 'Peru'],
  ['PHL', 'Philippines'],
  ['PLW', 'Palau'],
  ['PRI', 'Puerto Rico'],
  ['PRY', 'Paraguay'],
  ['PYF', 'French Polynesia'],
  ['REU', 'Réunion'],
  ['RWA', 'Rwanda'],
  ['SEN', 'Senegal'],
  ['SGP', 'Singapore'],
  ['SLB', 'Solomon Islands'],
  ['SLE', 'Sierra Leone'],
  ['SLV', 'El Salvador'],
  ['STP', 'Sao Tome and Principe'],
  ['SUR', 'Suriname'],
  ['SWZ', 'Swaziland'],
  ['SYC', 'Seychelles'],
  ['TCA', 'Turks and Caicos Islands'],
  ['TCD', 'Chad'],
  ['TGO', 'Togo'],
  ['THA', 'Thailand'],
  ['TJK', 'Tajikistan'],
  ['TLS', 'Timor-Leste'],
  ['TON', 'Tonga'],
  ['TTO', 'Trinidad and Tobago'],
  ['TUN', 'Tunisia'],
  ['TUV', 'Tuvalu'],
  ['TWN', 'Taiwan, Province of China'],
  ['TZA', 'Tanzania, United Republic of'],
  ['UGA', 'Uganda'],
  ['URY', 'Uruguay'],
  ['UZB', 'Uzbekistan'],
  ['VCT', 'Saint Vincent and the Grenadines'],
  ['VGB', 'Virgin Islands, British'],
  ['VIR', 'Virgin Islands, U.S.'],
  ['VNM', 'Viet Nam'],
  ['VUT', 'Vanuatu'],
  ['WLF', 'Wallis and Futuna'],
  ['WSM', 'Samoa'],
  ['ZAF', 'South Africa'],
  ['ZMB', 'Zambia'],
  ['ZWE', 'Zimbabwe']
]
export default codes
